Seek 1148/open source test lib
seek-ret/tests-rtl pull request #2
Opened 2021-04-07 14:19 UTC by barweiss

2021-04-07 15:15 UTC, guyarb requested changes

2021-04-07 15:15 UTC, guyarb commented on setup.py
> +      version='0.0.0-alpha',
0.1.0

2021-04-08 12:34 UTC, barweiss commented on setup.py
> +      version='0.0.0-alpha',
Fixed

2021-04-08 12:34 UTC, guyarb approved these changes

2021-04-08 12:35 UTC, merged